### PR TITLE
use larger font, less padding so more outer space :)

### PR DESCRIPTION
**Pull request by r10s**
targets #6

### CODE REVIEW

**Review by rosano — COMMENTED** [review]
Looks much better. I think there's too much bottom padding on mobile, the top will also take up half the screen—since the info background is transparent it could be 0; I would minimize the need to scroll.

A mistake in my suggestion from the other PR: I meant `lighter` to be only for the header rows, but it seems to have been applied to all text and not the header rows. Not so readable IMO:

Screen Shot 2022-12-19 at 09 14 47

**Comment by rosano** [comment]
Sorry, was cleaning my local branches and accidentally deleted this.

**Comment by r10s** [comment]
> A mistake in my suggestion from the other PR: I meant lighter to be only for the header rows, but it seems to have been applied to all text and not the header rows. Not so readable IMO:

fixed that.

let's merge this pr in as it is a huge improvement in readability. we can continue tweaking in subsequent pr.

**Comment by r10s** [comment]
i am wondering if we should not just say `git` for the link-text of (most) links in the right column. that would reduce clutter. the shown path fragments are mostly meaningless imho.

**Comment by rosano** [comment]
> i am wondering if we should not just say `git` for the link-text of (most) links in the right column. that would reduce clutter. the shown path fragments are mostly meaningless imho.

For [better accessibility](https://usability.yale.edu/web-accessibility/articles/links#link-text), I practice using unique text per link. The path fragments are probably not so important for most people, but it can help remind which organization repos are under (I can never predict where things are)—I'd rather have some information than repeated text like 'source code', which is implied by being in that column. We could also consider it as a sort of 'open API' by leaving data there for other people to do something with.

**Comment by r10s** [comment]
> For [better accessibility](https://usability.yale.edu/web-accessibility/articles/links#link-text), I practice using unique text per link.

hm, but this is bad for non-accessibility as it is pretty clear that it belongs to the left header. isn't there some accessibility attribute or so? this must be a very common problem, eg. if you have "X" or "Delete" buttons.

**Comment by rosano** [comment]
> isn't there some accessibility attribute or so?

You might be thinking of `aria-label`? If I were to use that to describe link text here I would write something that speaks nicely for screen readers, such as `delta-pages repo in the deltachat organization` (probably sounds better than speaking `deltachat/delta-pages`), but I think it's overkill for this project.

> this must be a very common problem, eg. if you have "X" or "Delete" buttons beside some element.

Obviously many apps do this and it can work well, but I believe it's generally an anti-pattern to repeat delete buttons as one must rely on the position to know you are deleting what you think you are deleting—there is less ambiguity when there's only one on screen at any given time, and this also serves as 'unique' link text.

**Comment by r10s** [comment]
"delete" was just one example. can be edit, move, whatever buttons. i doubt it is practically avoidable to have rows with the same buttons in UI we have today in common and users are used to.

> You might be thinking of aria-label? If I were to use that to describe link text here I would write something that speaks nicely for screen readers, such as delta-pages repo in the deltachat organization (probably sounds better than speaking deltachat/delta-pages), but I think it's overkill for this project.

compared to the effort already done, this is probably fine. don't most screenreaders also read out `tooltip`? that way, things would also be "visible" for non-screenreaders (in general, unless unavoidable, i prefer accessibility things also be used in visual view - that way we devs get aware if things are broken:)

**Pull request merged**
